/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RodzicRouteImport } from './routes/rodzic'
import { Route as IndexRouteImport } from './routes/index'

const RodzicRoute = RodzicRouteImport.update({
  id: '/rodzic',
  path: '/rodzic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rodzic': typeof RodzicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rodzic': typeof RodzicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rodzic': typeof RodzicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rodzic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rodzic'
  id: '__root__' | '/' | '/rodzic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RodzicRoute: typeof RodzicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rodzic': {
      id: '/rodzic'
      path: '/rodzic'
      fullPath: '/rodzic'
      preLoaderRoute: typeof RodzicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RodzicRoute: RodzicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
